<?php

use App\Http\Controllers\AiAgentController;
use App\Http\Controllers\AiPlanningController;
use App\Http\Controllers\ApiTokenController;
use App\Http\Controllers\ApprovalsController;
use App\Http\Controllers\Auth\PasswordResetController;
use App\Http\Controllers\Auth\SessionController;
use App\Http\Controllers\DemandController;
use App\Http\Controllers\DemandDeliveryEvidenceController;
use App\Http\Controllers\DemandReviewController;
use App\Http\Controllers\DemandTaskController;
use App\Http\Controllers\KnowledgeController;
use App\Http\Controllers\PerformanceReviewController;
use App\Http\Controllers\TeamActivityController;
use App\Http\Controllers\TeamCapacityController;
use App\Http\Controllers\TeamInvitationController;
use App\Http\Controllers\TeamMemberController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/painel');
Route::get('/revisao/{token}', [DemandReviewController::class, 'show'])->middleware('throttle:30,1')->name('client-reviews.show');
Route::get('/revisao/{token}/material', [DemandReviewController::class, 'material'])->middleware('throttle:60,1')->name('client-reviews.material');
Route::post('/revisao/{token}/respostas', [DemandReviewController::class, 'respond'])->middleware('throttle:10,1')->name('client-reviews.respond');
Route::get('/convite/{token}', [TeamInvitationController::class, 'show'])->middleware('throttle:30,1')->name('team-invitations.show');
Route::post('/convite/{token}', [TeamInvitationController::class, 'accept'])->middleware('throttle:5,1')->name('team-invitations.accept');
Route::middleware('guest')->group(function (): void {
    Route::get('/entrar', [SessionController::class, 'create'])->name('login');
    Route::post('/entrar', [SessionController::class, 'store'])->middleware('throttle:5,1');
    Route::get('/senha/esqueci', [PasswordResetController::class, 'requestForm'])->name('password.request');
    Route::post('/senha/email', [PasswordResetController::class, 'sendLink'])->middleware('throttle:3,1')->name('password.email');
    Route::get('/senha/redefinir/{token}', [PasswordResetController::class, 'resetForm'])->name('password.reset');
    Route::post('/senha/redefinir', [PasswordResetController::class, 'reset'])->middleware('throttle:5,1')->name('password.update');
});

Route::middleware(['auth', 'active'])->group(function (): void {
    Route::get('/painel', fn () => view('dashboard'))->name('dashboard');
    Route::resource('demandas', DemandController::class)->only(['index', 'create', 'store', 'show'])->names('demands')->parameters(['demandas' => 'demand']);
    Route::patch('/demandas/{demand}/etapa', [DemandController::class, 'updateStatus'])->name('demands.status');
    Route::post('/demandas/{demand}/evidencias-entrega', [DemandDeliveryEvidenceController::class, 'store'])->name('demands.delivery-evidence.store');
    Route::patch('/demandas/{demand}/cliente', [DemandController::class, 'assignClient'])->name('demands.client.assign');
    Route::get('/tarefas/quadro', [DemandTaskController::class, 'board'])->name('demand-tasks.board');
    Route::get('/aprovacoes', [ApprovalsController::class, 'index'])->name('approvals.index');
    Route::post('/demandas/{demand}/planejamento-ia', [AiPlanningController::class, 'propose'])->middleware('throttle:3,1')->name('ai-planning.propose');
    Route::post('/demandas/{demand}/planejamento-ia/{run}/aprovar', [AiPlanningController::class, 'approve'])->name('ai-planning.approve');
    Route::delete('/demandas/{demand}/planejamento-ia/{run}', [AiPlanningController::class, 'discard'])->name('ai-planning.discard');
    Route::post('/demandas/{demand}/assistente', [AiAgentController::class, 'ask'])->middleware('throttle:3,1')->name('ai-agent.ask');
    Route::get('/demandas/{demand}/assistente/{run}/status', [AiAgentController::class, 'status'])->name('ai-agent.status');
    Route::get('/assistente-agencia', [AiAgentController::class, 'organizationIndex'])->name('organization-assistant.index');
    Route::post('/assistente-agencia', [AiAgentController::class, 'askOrganization'])->middleware('throttle:3,1')->name('organization-assistant.ask');
    Route::get('/assistente-agencia/{run}/status', [AiAgentController::class, 'organizationStatus'])->name('organization-assistant.status');
    Route::post('/demandas/{demand}/links-revisao', [DemandReviewController::class, 'store'])->name('demand-reviews.store');
    Route::delete('/demandas/{demand}/links-revisao/{reviewLink}', [DemandReviewController::class, 'revoke'])->name('demand-reviews.revoke');
    Route::get('/demandas/{demand}/links-revisao/{reviewLink}/material', [DemandReviewController::class, 'teamMaterial'])->name('demand-reviews.team-material');
    Route::post('/demandas/{demand}/tarefas', [DemandTaskController::class, 'store'])->name('demand-tasks.store');
    Route::post('/tarefas/{task}/cronometro/iniciar', [DemandTaskController::class, 'startTimer'])->name('demand-tasks.timer.start');
    Route::post('/tarefas/{task}/cronometro/pausar', [DemandTaskController::class, 'pauseTimer'])->name('demand-tasks.timer.pause');
    Route::post('/tarefas/cronometro/recuperar', [DemandTaskController::class, 'recoverTimer'])->name('demand-tasks.timer.recover');
    Route::patch('/tarefas/{task}/status', [DemandTaskController::class, 'updateStatus'])->name('demand-tasks.status');
    Route::patch('/tarefas/{task}/responsavel', [DemandTaskController::class, 'updateAssignee'])->name('demand-tasks.assignee');
    Route::patch('/tarefas/{task}/cronograma', [DemandTaskController::class, 'updateSchedule'])->name('demand-tasks.schedule');
    Route::get('/conhecimento', [KnowledgeController::class, 'index'])->name('knowledge.index');
    Route::post('/conhecimento', [KnowledgeController::class, 'store'])->name('knowledge.store');
    Route::get('/conhecimento/arquivados', [KnowledgeController::class, 'archived'])->name('knowledge.archived');
    Route::put('/conhecimento/{item}', [KnowledgeController::class, 'update'])->name('knowledge.update');
    Route::delete('/conhecimento/{item}', [KnowledgeController::class, 'archive'])->name('knowledge.archive');
    Route::post('/conhecimento/{item}/restaurar', [KnowledgeController::class, 'restore'])->name('knowledge.restore');
    Route::post('/conhecimento/{item}/atribuir', [KnowledgeController::class, 'assign'])->name('knowledge.assign');
    Route::patch('/onboarding/{assignment}/etapas/{step}', [KnowledgeController::class, 'toggleStep'])->name('knowledge.assignment-step');
    Route::get('/equipe', [TeamMemberController::class, 'index'])->name('team.index');
    Route::get('/integracoes/tokens', [ApiTokenController::class, 'index'])->name('api-tokens.index');
    Route::post('/integracoes/tokens', [ApiTokenController::class, 'store'])->middleware('throttle:5,10')->name('api-tokens.store');
    Route::delete('/integracoes/tokens/{token}', [ApiTokenController::class, 'destroy'])->name('api-tokens.destroy');
    Route::patch('/equipe/{member}/acesso', [TeamMemberController::class, 'updateAccess'])->name('team.members.access');
    Route::get('/equipe/producao', [TeamActivityController::class, 'index'])->name('team.activity');
    Route::get('/equipe/capacidade', [TeamCapacityController::class, 'index'])->name('team.capacity');
    Route::post('/equipe/capacidade/disponibilidade', [TeamCapacityController::class, 'setScheduledHours'])->name('team.capacity.schedule');
    Route::post('/equipe/capacidade/ausencias', [TeamCapacityController::class, 'addAbsence'])->name('team.capacity.absences.store');
    Route::delete('/equipe/capacidade/ausencias/{absence}', [TeamCapacityController::class, 'removeAbsence'])->name('team.capacity.absences.destroy');
    Route::get('/equipe/avaliacoes', [PerformanceReviewController::class, 'index'])->name('performance-reviews.index');
    Route::post('/equipe/avaliacoes', [PerformanceReviewController::class, 'store'])->name('performance-reviews.store');
    Route::post('/equipe/avaliacoes/{review}/respostas', [PerformanceReviewController::class, 'respond'])->name('performance-reviews.respond');
    Route::post('/equipe/convites', [TeamInvitationController::class, 'store'])->middleware('throttle:10,1')->name('team-invitations.store');
    Route::delete('/equipe/convites/{invitation}', [TeamInvitationController::class, 'revoke'])->name('team-invitations.revoke');
    Route::post('/sair', [SessionController::class, 'destroy'])->name('logout');
});
