<?php

use App\Enums\UserRole;
use App\Http\Controllers\AiAgentController;
use App\Http\Controllers\AiBriefingController;
use App\Http\Controllers\AiPlanningController;
use App\Http\Controllers\AiProviderSettingsController;
use App\Http\Controllers\AiSolutionController;
use App\Http\Controllers\ApiTokenController;
use App\Http\Controllers\ApprovalsController;
use App\Http\Controllers\Auth\PasswordResetController;
use App\Http\Controllers\Auth\SessionController;
use App\Http\Controllers\DemandAttachmentController;
use App\Http\Controllers\DemandController;
use App\Http\Controllers\DemandDeliveryEvidenceController;
use App\Http\Controllers\DemandModuleController;
use App\Http\Controllers\DemandModuleStepController;
use App\Http\Controllers\DemandReviewController;
use App\Http\Controllers\DemandTaskController;
use App\Http\Controllers\KnowledgeController;
use App\Http\Controllers\PerformanceReviewController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ServiceAccessController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\TeamActivityController;
use App\Http\Controllers\TeamCapacityController;
use App\Http\Controllers\TeamInvitationController;
use App\Http\Controllers\TeamMemberController;
use App\Http\Controllers\UserNotificationController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/painel');
Route::get('/revisao/{token}', [DemandReviewController::class, 'show'])->middleware('throttle:30,1')->name('client-reviews.show');
Route::get('/revisao/{token}/material', [DemandReviewController::class, 'material'])->middleware('throttle:60,1')->name('client-reviews.material');
Route::post('/revisao/{token}/respostas', [DemandReviewController::class, 'respond'])->middleware('throttle:10,1')->name('client-reviews.respond');
Route::get('/convite/{token}', [TeamInvitationController::class, 'show'])->middleware('throttle:30,1')->name('team-invitations.show');
Route::post('/convite/{token}', [TeamInvitationController::class, 'accept'])->middleware('throttle:5,1')->name('team-invitations.accept');
Route::middleware('guest')->group(function (): void {
    Route::get('/entrar', [SessionController::class, 'create'])->name('login');
    Route::post('/entrar', [SessionController::class, 'store'])->middleware('throttle:5,1');
    Route::get('/senha/esqueci', [PasswordResetController::class, 'requestForm'])->name('password.request');
    Route::post('/senha/email', [PasswordResetController::class, 'sendLink'])->middleware('throttle:3,1')->name('password.email');
    Route::get('/senha/redefinir/{token}', [PasswordResetController::class, 'resetForm'])->name('password.reset');
    Route::post('/senha/redefinir', [PasswordResetController::class, 'reset'])->middleware('throttle:5,1')->name('password.update');
});

Route::middleware(['auth', 'active'])->group(function (): void {
    Route::get('/painel', function (Request $request) {
        if ($request->user()->role === UserRole::Client) {
            return view('dashboard');
        }

        return redirect()->route('team.activity');
    })->name('dashboard');
    Route::get('/perfil', [ProfileController::class, 'index'])->name('profile.index');
    Route::get('/perfil/foto', [ProfileController::class, 'photo'])->name('profile.photo');
    Route::put('/perfil', [ProfileController::class, 'update'])->name('profile.update');
    Route::get('/notificacoes', [UserNotificationController::class, 'index'])->name('notifications.index');
    Route::post('/notificacoes/ler-todas', [UserNotificationController::class, 'markAllRead'])->name('notifications.read-all');
    Route::get('/notificacoes/{notification}', [UserNotificationController::class, 'open'])->name('notifications.open');
    Route::get('/configuracoes', [SettingsController::class, 'index'])->name('settings.index');
    Route::resource('demandas', DemandController::class)->only(['index', 'create', 'store', 'show'])->names('demands')->parameters(['demandas' => 'demand']);
    Route::post('/demandas/assistente-briefing', [AiBriefingController::class, 'suggest'])->middleware('throttle:5,1')->name('ai-briefing.suggest');
    Route::get('/tipos-aprovacao', [DemandModuleController::class, 'index'])->name('approval-modules.index');
    Route::post('/tipos-aprovacao', [DemandModuleController::class, 'store'])->name('approval-modules.store');
    Route::put('/tipos-aprovacao/{module}/campos', [DemandModuleController::class, 'updateFields'])->name('approval-modules.fields');
    Route::patch('/tipos-aprovacao/{module}/status', [DemandModuleController::class, 'toggle'])->name('approval-modules.toggle');
    Route::patch('/demandas/{demand}/etapa', [DemandController::class, 'updateStatus'])->name('demands.status');
    Route::patch('/demandas/{demand}/etapas-do-tipo/{stepKey}', [DemandModuleStepController::class, 'update'])->name('demands.module-steps.update');
    Route::post('/demandas/{demand}/evidencias-entrega', [DemandDeliveryEvidenceController::class, 'store'])->name('demands.delivery-evidence.store');
    Route::post('/demandas/{demand}/anexos', [DemandAttachmentController::class, 'store'])->name('demand-attachments.store');
    Route::get('/demandas/{demand}/anexos/{attachment}', [DemandAttachmentController::class, 'show'])->name('demand-attachments.show');
    Route::patch('/demandas/{demand}/cliente', [DemandController::class, 'assignClient'])->name('demands.client.assign');
    Route::get('/tarefas/quadro', [DemandTaskController::class, 'board'])->name('demand-tasks.board');
    Route::get('/aprovacoes', [ApprovalsController::class, 'index'])->name('approvals.index');
    Route::post('/demandas/{demand}/planejamento-ia', [AiPlanningController::class, 'propose'])->middleware('throttle:3,1')->name('ai-planning.propose');
    Route::post('/demandas/{demand}/solucao-sugerida-ia', [AiSolutionController::class, 'generate'])->middleware('throttle:3,1')->name('ai-solution.generate');
    Route::post('/demandas/{demand}/planejamento-ia/{run}/aprovar', [AiPlanningController::class, 'approve'])->name('ai-planning.approve');
    Route::delete('/demandas/{demand}/planejamento-ia/{run}', [AiPlanningController::class, 'discard'])->name('ai-planning.discard');
    Route::post('/demandas/{demand}/assistente', [AiAgentController::class, 'ask'])->middleware('throttle:3,1')->name('ai-agent.ask');
    Route::get('/demandas/{demand}/assistente/{run}/status', [AiAgentController::class, 'status'])->name('ai-agent.status');
    Route::get('/assistente-agencia', [AiAgentController::class, 'organizationIndex'])->name('organization-assistant.index');
    Route::post('/assistente-agencia', [AiAgentController::class, 'askOrganization'])->middleware('throttle:3,1')->name('organization-assistant.ask');
    Route::get('/assistente-agencia/{run}/status', [AiAgentController::class, 'organizationStatus'])->name('organization-assistant.status');
    Route::post('/assistente/contextual', [AiAgentController::class, 'askContextual'])->middleware('throttle:5,1')->name('contextual-assistant.ask');
    Route::get('/configuracoes/ia', [AiProviderSettingsController::class, 'index'])->name('ai-settings.index');
    Route::put('/configuracoes/ia', [AiProviderSettingsController::class, 'update'])->name('ai-settings.update');
    Route::post('/configuracoes/ia/teste', [AiProviderSettingsController::class, 'test'])->middleware('throttle:3,1')->name('ai-settings.test');
    Route::post('/demandas/{demand}/links-revisao', [DemandReviewController::class, 'store'])->name('demand-reviews.store');
    Route::delete('/demandas/{demand}/links-revisao/{reviewLink}', [DemandReviewController::class, 'revoke'])->name('demand-reviews.revoke');
    Route::get('/demandas/{demand}/links-revisao/{reviewLink}/material', [DemandReviewController::class, 'teamMaterial'])->name('demand-reviews.team-material');
    Route::post('/demandas/{demand}/tarefas', [DemandTaskController::class, 'store'])->name('demand-tasks.store');
    Route::post('/tarefas/{task}/cronometro/iniciar', [DemandTaskController::class, 'startTimer'])->name('demand-tasks.timer.start');
    Route::post('/tarefas/{task}/cronometro/pausar', [DemandTaskController::class, 'pauseTimer'])->name('demand-tasks.timer.pause');
    Route::post('/tarefas/cronometro/recuperar', [DemandTaskController::class, 'recoverTimer'])->name('demand-tasks.timer.recover');
    Route::post('/tarefas/cronometro/sinal', [DemandTaskController::class, 'heartbeat'])->name('demand-tasks.timer.heartbeat');
    Route::patch('/tarefas/{task}/status', [DemandTaskController::class, 'updateStatus'])->name('demand-tasks.status');
    Route::patch('/tarefas/{task}/responsavel', [DemandTaskController::class, 'updateAssignee'])->name('demand-tasks.assignee');
    Route::patch('/tarefas/{task}/cronograma', [DemandTaskController::class, 'updateSchedule'])->name('demand-tasks.schedule');
    Route::get('/conhecimento', [KnowledgeController::class, 'index'])->name('knowledge.index');
    Route::post('/conhecimento', [KnowledgeController::class, 'store'])->name('knowledge.store');
    Route::get('/conhecimento/arquivados', [KnowledgeController::class, 'archived'])->name('knowledge.archived');
    Route::put('/conhecimento/{item}', [KnowledgeController::class, 'update'])->name('knowledge.update');
    Route::delete('/conhecimento/{item}', [KnowledgeController::class, 'archive'])->name('knowledge.archive');
    Route::post('/conhecimento/{item}/restaurar', [KnowledgeController::class, 'restore'])->name('knowledge.restore');
    Route::post('/conhecimento/{item}/atribuir', [KnowledgeController::class, 'assign'])->name('knowledge.assign');
    Route::patch('/onboarding/{assignment}/etapas/{step}', [KnowledgeController::class, 'toggleStep'])->name('knowledge.assignment-step');
    Route::get('/equipe', [TeamMemberController::class, 'index'])->name('team.index');
    Route::get('/equipe/acessos-servicos', [ServiceAccessController::class, 'index'])->name('service-access.index');
    Route::post('/equipe/acessos-servicos', [ServiceAccessController::class, 'store'])->name('service-access.store');
    Route::put('/equipe/acessos-servicos/{service}', [ServiceAccessController::class, 'update'])->name('service-access.update');
    Route::delete('/equipe/acessos-servicos/{service}', [ServiceAccessController::class, 'archive'])->name('service-access.archive');
    Route::post('/equipe/acessos-servicos/{service}/restaurar', [ServiceAccessController::class, 'restore'])->name('service-access.restore');
    Route::post('/equipe/acessos-servicos/{service}/solicitacoes', [ServiceAccessController::class, 'requestAccess'])->name('service-access.request');
    Route::delete('/equipe/acessos-servicos/solicitacoes/{accessRequest}', [ServiceAccessController::class, 'withdraw'])->name('service-access.withdraw');
    Route::patch('/equipe/acessos-servicos/solicitacoes/{accessRequest}/decisao', [ServiceAccessController::class, 'decide'])->name('service-access.decide');
    Route::post('/equipe/acessos-servicos/solicitacoes/{accessRequest}/revogar', [ServiceAccessController::class, 'revoke'])->name('service-access.revoke');
    Route::get('/integracoes/tokens', [ApiTokenController::class, 'index'])->name('api-tokens.index');
    Route::post('/integracoes/tokens', [ApiTokenController::class, 'store'])->middleware('throttle:5,10')->name('api-tokens.store');
    Route::delete('/integracoes/tokens/{token}', [ApiTokenController::class, 'destroy'])->name('api-tokens.destroy');
    Route::patch('/equipe/{member}/acesso', [TeamMemberController::class, 'updateAccess'])->name('team.members.access');
    Route::patch('/equipe/{member}/especialidades', [TeamMemberController::class, 'updateSpecialties'])->name('team.members.specialties');
    Route::get('/equipe/producao', [TeamActivityController::class, 'index'])->name('team.activity');
    Route::get('/equipe/producao/agora', [TeamActivityController::class, 'now'])->name('team.activity.now');
    Route::get('/equipe/capacidade', [TeamCapacityController::class, 'index'])->name('team.capacity');
    Route::post('/equipe/capacidade/disponibilidade', [TeamCapacityController::class, 'setScheduledHours'])->name('team.capacity.schedule');
    Route::post('/equipe/capacidade/ausencias', [TeamCapacityController::class, 'addAbsence'])->name('team.capacity.absences.store');
    Route::delete('/equipe/capacidade/ausencias/{absence}', [TeamCapacityController::class, 'removeAbsence'])->name('team.capacity.absences.destroy');
    Route::get('/equipe/avaliacoes', [PerformanceReviewController::class, 'index'])->name('performance-reviews.index');
    Route::post('/equipe/avaliacoes', [PerformanceReviewController::class, 'store'])->name('performance-reviews.store');
    Route::post('/equipe/avaliacoes/{review}/respostas', [PerformanceReviewController::class, 'respond'])->name('performance-reviews.respond');
    Route::post('/equipe/convites', [TeamInvitationController::class, 'store'])->middleware('throttle:10,1')->name('team-invitations.store');
    Route::delete('/equipe/convites/{invitation}', [TeamInvitationController::class, 'revoke'])->name('team-invitations.revoke');
    Route::post('/sair', [SessionController::class, 'destroy'])->name('logout');
});
